---
title: 新目标，新征程，新的2021
authors:
  - EndlessPeak
tags:
  - Hugo
  - Org Mode
categories:
  - Build
series: []
date: 2021-01-09T18:05:00+08:00
lastmod: 2021-01-09T18:32:56+08:00
featuredVideo:
featuredImage:
draft: false
--- 

* 新目标，新征程，新的2021

** 回顾过去

站在年关的十字路口，我不禁回忆起刚刚结束的2020年——失败的一年，我这样称呼它，不是对今年忙于考研无暇做事的批判，而是对我所应当专注的事情不能全身心地投入而遗憾和愤恨。

梳理起去年年关所定下的雄心壮志，才发现自己竟然一个都未完成，这可真是小母牛的腿拉伸到了南极——拉胯到了极点。更惊奇于自己定的目标都是不切实际的幻想，以如今的眼光来看，根本不可能实现，也不知道我当初为何会定下如此荒谬的目标，也许是好高骛远习惯了吧。

我早就该做一些改变了，去年1月份的时候，我几乎踏上了正轨——我所认为的正轨，就是从POSIX标准开始，了解编程语言的前世今生，知道它为何而存在，最终的目的是何方。这是我个人认为最正统的路线——可惜，工欲善其事，必先利其器。在“利器”的过程中，我沉迷在缤纷多彩的配置和外观中无法自拔，追求金玉其外，结果败絮其中，错失了继续深入学习原理的时机——我真正的兴趣在计算机科学而不是软件工程——我认识到这一点花费的代价太大了。

我特别欣赏在 *The Hard way learn C* 中作者所说的一句话，IDE会使你变笨。我认为不仅仅是IDE，Windows 会使人变懒。我一直不能下定决心进入真正有兴趣的领域去学习，这是习惯使然，纠正会很困难，但好在我的信念是坚定的。即使我永远无法抵达，至少我不断地在尝试去拥抱它。

纵观去年一年，我觉得我最需要弥补的就是执行力。执行力是目标存在的价值之根本所在，如果我的执行力同我的信念一般坚定，不以其他人的意志为转移，那么我即使不能做到事事圆满，至少也会学有所成，而不必如现在这般，需要近乎重新开始。

** 把握现在

人最可贵的品质就是正视自己的错误。当然仅仅是这样是远远不够的。哲学认为认识的起点和归宿是实践，认识的目的是通过实践改造世界，认识之于实践有如识错之于改错。所以对我来说目前最重要的问题就是如何改错。

首先，加强行动，也就是执行力。我当前阶段编程学习的核心目标是夯实基础，做到“不动如山”。我给自己制定了下面的任务，时间期限就定在参加工作前完成：

毕业设计前:

- [ ] Python numpy & pandas
- [ ] *Machine Learning* 周志华
- [ ] Support Vector Machine implement
- [ ] Netural network implement

21.9前:

- [ ] *The hard way learn C*
- [ ] *The hard way learn Python*
- [ ] *C Programming language* 中文版 机械工业出版社 及习题解答

22.3前：

- [ ] C 程序设计语言 浙江大学教材
- [ ] C 程序设计语言 实验与习题解答 浙江大学教材
- [ ] *C Primer Plus Edition 6*
- [ ] *C Primer Plus Edition 6* 习题解答
- [ ] *Python Cookbook*

 #+begin_quote
 注：这些书有相当部分的内容是重复的，而且我有一定的C语言基础，学习起来会非常迅速，不会存在阅读任务完成不了的问题。
 #+end_quote 

** 展望未来

给自己的未来制定太多的束缚或者详细的目标是没有意义的，矛盾的特殊性限制了对未来具体形象的描绘，不过即使是伟大的共产主义事业，想象它的未来的乐趣也被马克思称作大错特错，因此我不会给出具体的发展目标，而只有一个大概的发展方向。

- C & C++、Java、Python、Golang等几种主流常见语言。
- 版本控制、虚拟化容器、构建工具、正则表达式等工具。
- 操作系统和计算机网络方面的理论和实践内容。

在进行毕业设计的过程中，我对未来的发展有了新的规划：

- 深度学习方向

