main:
  - name: 关于
    url: /authors
    weight: 1
  - name: 文章
    url: /posts/
    weight: 2
  - name: 文档
    url: /docs/
    weight: 3
  - name: 分类
    url: /categories
    weight: 4
  - name: 标签
    url: /tags
    weight: 5
  - name: 系列
    url: /series
    weight: 6
